[package]
name = "learn-deep-learning"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = { version = "0.8.0", features = ["metal"] }
polars = {version = "0.44", features = ["lazy", "ndarray"]}
